INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SolePower", 'Wearable' , 50000, 25,55);

INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);
INSERT INTO users (name, age) VALUES ("Devin",25);

INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50000,5,7);
